name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, dev ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry==2.2.1

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: Run Linter
        run: |
          poetry run ruff check --output-format=github .

      - name: Run Formatter
        run: |
          poetry run ruff format --check .
